### PR TITLE
remove console log

### PR DESCRIPTION
**Pull request by shashank-sachan**

### CODE REVIEW

**Comment by BogdanDarius** [comment]
This PR is not present in the lastest npm version of svelte-slidy.

**Comment by BogdanDarius** [comment]
This PR is not present in the lastest version of svelte-slidy when getting it from npm.

**Comment by BogdanDarius** [comment]
This PR is not present in the latest version of svelte-slidy when getting it from npm.

**Comment by BogdanDarius** [comment]
This PR is not present in the latest version of svelte-slidy from npm.

**Comment by Valexr** [comment]
Do the logs hang again?

**Comment by BogdanDarius** [comment]
The master is fine, but npm module is not up-to-date.
Here is a quick preview:
fresh_install

**Comment by Valexr** [comment]
Ups... thnx👍🏻check it

**Comment by Valexr** [comment]
Publish without console.log() 🤓
Tx @BogdanDarius 👍🏻

**Comment by Valexr** [comment]
If you not hard check please 🤓

**Comment by BogdanDarius** [comment]
logging is gone. thank you!

**Comment by Valexr** [comment]
👍🏻

**Pull request merged**
