### PR TITLE
Make event handlers passive

### PR DESCRIPTION
**Pull request by Pho3nixHun**
I dicovered this issue in Lighthouse (Chrome dev tools), so since it's an easy fix and it seemingly doesn't break anything I provide this PR.

### CODE REVIEW

**Comment by Valexr** [comment]
O, txs👍🏻I’m not tested in LH...
Merged🤓

May be you have idea about accelerated drag scroll?

**Comment by Pho3nixHun** [comment]
What are the reproduction steps? I haven't seen any bug with it yet.

**Comment by Valexr** [comment]
Power of drag swipe > accelerate scroll speed... if you have idea to implementation 

& true bug - if often drags with minimal paused slides shuffle without animation...

**Comment by Valexr** [comment]
Don’t forget update version to 2.3.8

**Comment by Valexr** [comment]
Create theme in discussion https://github.com/Valexr/svelte-slidy/discussions/7

**Comment by Pho3nixHun** [comment]
I was about updating the version, but I suppose it's not a big fix for a step in version. Or was it a comment for yourserlf? 😄

**Comment by Valexr** [comment]
What you have version?

**Comment by Pho3nixHun** [comment]
I usually do ```git fetch upstream && git merge upstream/master``` on my fork, so I must be somewhere around the latest version, but it does not matter, since I would get a merge conflict in case of conflicting changes. :)

**Comment by Valexr** [comment]
Okey. ✌🏻Any idea about bug & accelerate?

**Pull request merged**
